spring.application.name=QuickLink

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.datasource.url=jdbc:mysql://localhost:3306/quicklink
spring.datasource.username=root
spring.datasource.password=A_kit1087pc

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true